
database:
  host: "localhost"
  port: "5432"
  username: "your_username"
  password: "your_password"
  database_name: "devices"
  connection_pool_size: 5
scanner:
  # нужно всегда ставить trailing / !!!!!!!
  input_directory_absolute_path: "/home/timohahaa/projects/device-service/in/"
  # нужно всегда ставить trailing / !!!!!!!
  output_directory_absolute_path: "/home/timohahaa/projects/device-service/out/"
  rescan_duration_in_seconds: "60s"
